// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';

export function AreOsuAuthCredentialsSet():Promise<boolean>;

export function GetUser(arg1:string):Promise<model.User>;

export function SetGameMode(arg1:string):Promise<void>;

export function SetOsuAuthCredentials(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
