// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {model} from '../models';
import {context} from '../models';

export function AreOsuAuthCredentialsSet():Promise<boolean>;

export function CreateNewClient():Promise<void>;

export function GetCredentials():Promise<app.osuAuthCredentials>;

export function GetStatsUpdates(arg1:number):Promise<Array<model.UserStats>>;

export function GetUser(arg1:string):Promise<model.MyUserStruct>;

export function IsClientValid():Promise<boolean>;

export function SaveOsuAuthCredentials(arg1:string,arg2:string):Promise<void>;

export function SavePlayerData(arg1:string):Promise<void>;

export function SetGameMode(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
