// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AreOsuAuthCredentialsSet() {
  return window['go']['app']['App']['AreOsuAuthCredentialsSet']();
}

export function GetUser(arg1) {
  return window['go']['app']['App']['GetUser'](arg1);
}

export function SetGameMode(arg1) {
  return window['go']['app']['App']['SetGameMode'](arg1);
}

export function SetOsuAuthCredentials(arg1, arg2) {
  return window['go']['app']['App']['SetOsuAuthCredentials'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}
